services:
  next-app:
    container_name: next-app
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
    # Set environment variables directly in the docker-compose file
    environment:
      ENV_VARIABLE: ${ENV_VARIABLE}
      NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    env_file:
      - "../../.env"
    volumes:
      - "staticbuild:/app/node_modules"
      - "../.././:/app/"
    restart: always
    ports:
      - 3000:3000
    networks:
      - development_networks

  nginx:
    build:
      context: ../../nginx
      # dockerfile: nginx/Dockerfile
    depends_on:
      - next-app
    ports:
      - 80:80
    networks:
      - development_networks

networks:
  development_networks:
    driver: bridge

volumes:
  staticbuild:
